### ISSUE TITLE
*spelling error

### ISSUE THREAD

**Issue by sushilfenin** [AlekEagle/dadbot#35]
misspelled 'orange' in data/lists.json 
![image](https://user-images.githubusercontent.com/69116298/197366835-02cd7461-7d75-4bfe-9183-3b3bef20b354.png)

**Comment by sushilfenin** [comment]
sorry for correcting, dad

**Comment by AlekEagle** [comment]
I misspelt that intentionally to emphasize how sloppy the "advice" is.
